### ISSUE TITLE
removing item doesn't work

### ISSUE THREAD

**Issue by xeospeed** [seanfuture/aware-feedback#25]
<img src="https://avatars.githubusercontent.com/u/791414?v=3" width="48" height="48"> **Reported by matthewkrivanek**

![screen shot](https://s3-us-west-2.amazonaws.com/getupdraft/projects/104/builds/C314D243-EB38-4769-B242-AB9ACA852193/feedback/9b06194e-dee4-4741-994c-7bb6e53d5100.png)

> Tried swiping to remove item. Does nothing. 
- OS: 9.3.2
- Device: iPhone 6s Plus
- Size: 5.5 Inches
- Region: US

---

<sub>Posted via [Updraft](https://www.getupdraft.io)</sub>

**Comment by seanfuture** [comment]
Thanks for finding - swipe in that particular mode ( options / special instructions ) should be disabled .. easy fix .. ty

[--- Commented from Asana.com
#commenter Sean Harms
---[aa]
